#define present_LOGER_1                  1
#define present_TIME_CONTROL_1           1
#define present_FACTORY_SET_1            1
#define present_POWER_ON_PUSK_1          1
#define present_PAROLES_1                1
#define present_UF5_F2S_1                1
#define present_TEMP_LSU_2_1             1
#define present_BASE_CALC_1              1
#define present_MB_0X05_1                1
#define present_OR-2_1                   1
#define present_AIN_SCALE_V3_1           1
#define present_PORT_UART_3_1            1
#define present_PERIF_V2_1               1
#define present_LOAD_LOSS_1              1
#define present_DRV_UD_1                 1
#define present_S16_S16_TO_S16_1         1
#define present_BIT8_TO_U16_1            1
#define present_TPM_1                    1
#define present_ADD_2                    1
#define present_LOCAL_APV_V3_1           1
#define present_RTC_1                    1
#define present_KX+B_32_2_1              1
#define present_FREQLIMITCHECK_1         1
#define present_TEMP_CONTROL_1           1
#define present_CURRENT_IMBALANCE_1      1
#define present_FB_COMBO_1               1
#define present_BOOTLOADER_1             1
#define present_DRV_V5_1                 1
#define present_FREQ_SCALE_1             1
#define present_GET_CRC_PO_1             1
#define present_BASE16_1                 1
#define present_DIN_UP_DOWN_1            1
#define present_SEL_REF_V2_1             1
#define present_MIN_MAX_LIMITER_1        1
#define present_REF_CONTROL_1            1
#define present_LED_CONTROL_1            1
#define present_FREQ_FORBIDDEN_V2_1      1
#define present_DISKR_FUNC_V4_1          1
#define present_APV1_1                   1
#define present_TORQUE_MAX_1             1
#define present_KX+B_1                   1
#define present_WARNINGS_1               1
#define present_EXT_BLOCKS_PARAMS_1      1
#define present_DIN_2U64_1               1
#define present_CONTROL_V2_1             1
#define present_UNDERLOAD_1              1
#define present_BIT16_TO_U16_1           1
#define present_FAIL_COMMON_V2_1         1
#define present_LED_WIFI_1               1
#define present_SVP_UNIT_1               1
#define present_KOEFF_RS1_1              1
#define present_MUX24_1                  1
#define present_MUX8_2_1                 1
#define present_OR-4_1                   1
#define present_PID_REF_CONVERT_1        1
#define present_MIN_MAX_2_2              1
#define present_MUX4_2                   1
#define present_PID_IQ_1                 1
#define present_READY_STATUS_1           1
#define present_POWER_LOSS_APV_1         1
#define present_OR-3_1                   1
#define present_MB_0X05_VAL_1            1
#define present_PULSE_RISE_PRM_1         1
#define present_FAULT_WARNING_1          1
#define present_JRN_V2_1                 1
#define present_MUX2_1                   1
#define present_LED_RUN_1                1
#define present_MULL_1                   1
#define present_TORMOZ_V2_1              1
#define present_NAMEFUNC16_1             1
#define present_RW_GROUP_PRM_1           1
#define present_BRAKE_CNTRL_1            1
#define present_PICKUP_V2_1              1
#define present_MUX_4X4_4_1              1
#define present_FUNCTIONAL_BLOCK_1       1
#define present_CURRENT_CONTROL_1        1
#define present_DEBUG_SYM_1              1
#define present_RAMP_CTRL_MOD2_1         1
#define present_CONT_FAIL_1              1
#define present_LIFT_CMD_V3_1            1
#define present_START_STOP_MUX_1         1
#define present_EVAK_V3_1                1
#define present_NO_FLOW_DR_RUN2_1        1
#define present_ENCO_PHASING_BLOCK_1     1
#define present_DERATING_CONTROL_1       1
#define present_PUSK_READY_2_1           1
#define present_STOP_2_1                 1
#define present_END_OF_CURVE_1           1
// 87
